Ecommers/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace="home")),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteObjectBucket.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadObjectBucket.as_view(), name='download_obj_bucket'),
    path('upload_obj/', views.UploadObjectBucket.as_view(), name='upload_obj_bucket'),

]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(), name='order_create'),
    path('detaile/<int:order_id>',views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>',views.OrderPayView.as_view(), name='order_pay'),
    path('verify/',views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>',views.CouponApplyView.as_view(), name='coupon_apply')
]

home/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    sub_category=models.ForeignKey('self',on_delete=models.CASCADE,related_name='scategories',null=True,blank=True)
    is_sub=models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])

class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:product_detail',args=[self.slug])

home/forms.py
from django import forms


class UploadObjBucket(forms.Form):
    upload_file = forms.CharField(max_length=1000)

home/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from utils import IsAdminMixin
from .models import Product, Category
from . import tasks
from . import forms
from orders.forms import CartAddForm

# Create your views here.
class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category=Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'home/home.html', {'products': products,'categories': categories})


class ProductsDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form=CartAddForm()
        return render(request, 'home/details.html', {'product': product,'form':form})


class BucketView(IsAdminMixin, View):
    def get(self, request):
        form = forms.UploadObjBucket()
        objects = tasks.all_bucket_object_task()
        return render(request, 'home/bucket.html', {'objects': objects, 'form': form})


class DeleteObjectBucket(IsAdminMixin, View):
    def get(self, request, key):
        tasks.delete_bucket_object_task.delay(key)
        messages.success(request, 'your image will be delete', 'info')
        return redirect('home:bucket')


class DownloadObjectBucket(IsAdminMixin, View):
    def get(self, request, key):
        tasks.download_bucket_object_task.delay(key)
        messages.success(request, 'your file will be downloaded', 'info')
        return redirect('home:bucket')


class UploadObjectBucket(View):
    def get(self, request):
        tasks.upload_bucket_object_task.delay(req=request.GET['upload_file'])
        messages.success(request, 'your file will be uploaded', 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'home:upload_obj_bucket' %}" method="get">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="send">
    </form><br>


    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for object in objects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td >{{ object.Key }}</td>
                <td >{{ object.Size|filesizeformat }}</td>
                <td ><a href="{% url 'home:download_obj_bucket' object.Key %}">download</a></td>
                <td ><a href="{% url 'home:delete_obj_bucket' object.Key %}">delete</a></td>
            </tr>
        {% endfor %}


        </tbody>
    </table>
{% endblock %}

home/templates/home/details.html
{% extends 'base.html' %}

{% block body %}
    <h2>{{ product.name }}</h2>
    <p>{{ product.price }} Toman</p>
    <small> {{ product.created }}</small><br>
    <img src="{{ product.image.url }}" alt="" width="20%" height="20%">
    <h5>{{ product.description }}</h5><br><br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add to cart">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
    {% for category in categories %}
        <!-- Example split danger button -->
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" type="button" class="btn btn-info">{{ category.name }}</a>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
                    aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% for sub in category.scategories.all %}
                    <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>

                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <br><br>
    {% for product in products %}
        <div class="card" style="width: 18rem; display:inline-block;">
        <img src="{{ product.image.url }}" class="card-img-top" alt="#">
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Detail</a>
        </div>
    {% endfor %}
</div>
{% endblock %}