Ecommers/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace="home")),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('verify/',views.UserVerifyCodeView.as_view(),name='user_verify'),
    path('logout/',views.UserLogOutView.as_view(),name='user_logout'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteObjectBucket.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadObjectBucket.as_view(), name='download_obj_bucket'),
    path('upload_obj/', views.UploadObjectBucket.as_view(), name='upload_obj_bucket'),

]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(), name='order_create'),
    path('detaile/<int:order_id>',views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>',views.OrderPayView.as_view(), name='order_pay'),
    path('verify/',views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>',views.CouponApplyView.as_view(), name='coupon_apply')
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}"> {{ msg }}</p>
    {% endfor %}
{% endif%}

templates/inc/navbar.html
<header class="navbar navbar-expand-lg bg-body-tertiary">

    <div class="col-2 content1">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
            </li>

        </ul>
    </div>
    <form class="d-flex" role="search" method="get" novalidate>
        {{ form_nav }}
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <ul class="nav justify-content-end">
        {% if request.user.is_admin %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:bucket' %}">bucket</a>
            </li>
        {% endif %}

        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_logout' %}">logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Profile</a>
            </li>
        {% else %}
            <li class="nav justify-content-end">
                <a class="nav-link active" aria-current="page"
                   href="{% url 'accounts:user_login' %}">login</a>
            </li>
            <li class="nav justify-content-end">
                <a class="nav-link" aria-current="page"
                   href="{% url 'accounts:user_register' %}">Register</a>
            </li>
        {% endif %}
        <li class="nav justify-content-end">
            <a class="nav-link" aria-current="page"
               href="{% url 'orders:cart' %}" style="color:brown;">CART {{ cart|length  }}</a>

        </li>

    </ul>

    <ul class="nav justify-content-end">


    </ul>


</header>